# Basic
title: hegk
subtitle: A blog-orientation theme for hegk
welcome_message: <a href="https://github.com/hegk" target="_blank"></a>
description: hegk is a iOS developer.
creator: <a href="https://hegk.github.io/">@hegk</a>

url: "https://hegk.github.io/"

permalink: /:year/:month/:day/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'https://github.com/hegk/'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
     disqus: hegk
    # duoshuo: 
# Social
social:
    github: https//github.com/hegk
    mail: mission550w@gmail.com

# Google Analytics
#ga:
    # id: your_ga_id
    # host: your_host
